name: Continuous Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Balena Push
      uses: theaccordance/balena-push@v1.0.0
      with:
        api-token: ${{ secrets.BALENA_API_TOKEN }}
        application-name: WordClock
